### ISSUE TITLE
 Can't scroll while creating customer

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/Fineract-CN-mobile#116]
**Summary:** 

Can't scroll to bottom to see other fields when keyboard is visible(e.g. customer address).
User can't scroll form while creating the customer. 
User should able to scroll down up when keyboard id visible

**Comment by nb2998** [comment]
@therajanmaurya 
Does this solve the issue?

![20180114_153931](https://user-images.githubusercontent.com/25134501/34914894-da33b16c-f941-11e7-945b-dcda2fce832d.gif)

**Comment by therajanmaurya** [comment]
Good work :)

**Comment by nb2998** [comment]
Thank you so much! :)
