### ISSUE TITLE
Unable to login with the provided credentials

### ISSUE THREAD

**Issue by batbrain7** [openMF/Fineract-CN-mobile#169]
**Summary:** 

The credentials provided in the Wiki cannot login in the app.

**Steps to reproduce:** 

Enter the credentials in the wiki after installing the app.

**Expected behavior:** 

Should've logged me in

**Observed behavior:** 

a prompt message saying "Wrong Username or password" and unable to login using the provided credentials.

**Device and Android version:** 

Samsung Galaxy J2(2016)  Android version : 6.0.1

**Comment by therajanmaurya** [comment]
@batbrain7 Please I have updated the credentials that are targeting the different endpoint. If you want to just test the app, Download the wiki APK and run with given credentials otherwise wait.. very soon we are going setup a demo user with the already present endpoint in code.
