### ISSUE TITLE
Bug in Roles/Permissions activity 

### ISSUE THREAD

**Issue by ojasgulati** [openMF/Fineract-CN-mobile#171]
**Summary:** 

**Summarize your issue in one sentence (what goes wrong, what did you expect to happen)**

when user press the back button in time of loading the content of roles tab app crashes
![20180105_180304](https://user-images.githubusercontent.com/23313191/34609749-f17c2f5c-f243-11e7-891d-27d15a8fa9ae.gif)

**What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?**

 I have test it on real device (as shown in gif) running android 5.1 and on emulator runnig android 8.0. App crashes on both.

**Would you like to work on it?**
Yes

**Comment by therajanmaurya** [comment]
Good Catch, It is an issue. To fix this issue please override the attachView and detachView method in RolesPresenter and what you have to call inside the method please check this presenter : https://github.com/openMF/Fineract-CN-mobile/blob/development/app/src/main/java/org/apache/fineract/ui/online/login/LoginPresenter.java
