### ISSUE TITLE
No Ok/Cancel buttons in DatePicker for Date of birth

### ISSUE THREAD

**Issue by nb2998** [openMF/Fineract-CN-mobile#174]
**Summary:** 

Ok and Cancel buttons not visible in Datepicker dialog in Customer Details form

**Steps to reproduce:** 

View Customer -> Click on any customer -> Edit-> Click on Date of birth

**Expected behavior:** 

Ok and Cancel buttons should be visible

**Device and Android version:** 

OnePlus 5, Android 7.1.1

**Screenshots:** 

![screenshot_20180109-230954](https://user-images.githubusercontent.com/25134501/34734919-92dd8894-f593-11e7-89dd-ae5394952848.jpg)

**Would you like to work on this?**

Yes

**Comment by therajanmaurya** [comment]
Yes, you can, Simple hint it is happening because of style.

**Comment by devendraaparnathi** [comment]
This is because of your text color is default set as white color,
change in your <base application theme>
        <item name="colorPrimary">"YOUR COLOR"</item>
        <item name="colorPrimaryVariant">"YOUR COLOR"</item>
