### ISSUE TITLE
Invalid values are accepted for the date of birth of a customer

### ISSUE THREAD

**Issue by AbhilashG97** [openMF/Fineract-CN-mobile#175]
**Summary:** 

Invalid values are accepted for ```Date of birth``` of a customer. The issue persists when the user creates a new customer and when the user edits the details of a customer. 

**Steps to reproduce:** 

1. Open the application
1. Tap on ```View Customer```
1. Select a customer 
1. Tap on the edit button
1. Tap on the ```Date of birth``` field and select an invalid date of birth (e.g ```24/05/2030```) 

**Expected behavior:** 

The field shouldn't accept invalid values for the date of birth of a customer

**Observed behavior:** 

The field currently accepts invalid values for ```Date of birth``` of a customer. 

**Device and Android version:** 

Device : Xiaomi Mi A1 [tissot]
ROM : Stock Android [Oreo 8.0.0]

**GIF:** 

![videotogif_2018 01 10_21 07 39](https://user-images.githubusercontent.com/20839661/34781262-5ead472c-f64b-11e7-9d36-7f9202a96ed4.gif)

**Comment by AbhilashG97** [comment]
I would like to work on this issue.

**Comment by therajanmaurya** [comment]
Go ahead @AbhilashG97.
