### ISSUE TITLE
User Guide for Deposit Account list Feature 

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/Fineract-CN-mobile#184]
**Summary:** 

Document the Deposit Account list Feature.

As any community will decide to implement in his society they would need to some documentation so their field officer can learn how efficiently they can use the app.

Make Google Doc and share the link, like we are decided to where we are going to put these docs.

Here is an example of Android-client documentation, you can get an idea how you have to write.
https://mifosforge.jira.com/wiki/spaces/docs/pages/76873780/Mifos+Android+Client+User+Guide

Here you can download the APK and you can find credentials too
https://github.com/openMF/Fineract-CN-mobile/wiki

Here is the blog post you can get some help.
https://medium.com/@therajanmaurya/apache-gsoc-2017-blog-post-f2791dc136b5

**Comment by AkashBhave** [comment]
I have creating a page documenting this feature here:
https://cwiki.apache.org/confluence/display/FINERACT/Deposit+Account+Feature#

This issue, along with #185 and #186, can be resolved. 👍

**Comment by therajanmaurya** [comment]
@AkashBhave I have seen you documentation that is awesome. 

Please make little changes 

In Point 1, you mentioned only one way to go on customer list please add documentation to go to customer list from Navigation Drawer that should be first way because dashboard is not fixed now. It will be change according to requirement and time.

In section Creating a New Deposit Account 

In Point 1 “This will launch the new deposit account page.” It should be “This will launch the new deposit account creation form.”

In Point 2,  Rename “Image 1” t0 “Figure 1” and “Image 2”  to “Figure 2”.

you second point would be 
“2. Select a product (Figure 1) and search beneficiary (Figure 2).”

Please add, How user can edit deposit account too.

and Let me know.

**Comment by AkashBhave** [comment]
Thanks @therajanmaurya for the feedback. I have updated my page with all the changes that you requested.

**Comment by therajanmaurya** [comment]
Added documentation : https://cwiki.apache.org/confluence/display/FINERACT/View+List+of+Deposit+Accounts
