### ISSUE TITLE
Showing Null at place Assigned Employee in Customer Detail View

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/Fineract-CN-mobile#203]
**Summary:** 

As you will open any customer details (Jone Doe) for no employee assigned then you can see the ```null```.  It should show ```Not Assigned```.

it is working fine for other but for this customer not. 

**Steps to reproduce:** 

Go to customer list and click on the customer (Jone Due) that does not have any assigned employee. you will see null.

**Expected behavior:** 

It should have text ```Not Assigned``` instead of ```null```

**Observed behavior:** 
showing ```null``` instead of ```Not Assigned```

**Device and Android version:** 

Moto G turbo

**Screenshots:** 

![image](https://user-images.githubusercontent.com/5724482/34998641-a7c8f80c-fb05-11e7-811a-834a8b8ebd29.png)
![image](https://user-images.githubusercontent.com/5724482/34999077-bcdfe484-fb06-11e7-8b64-0f53069a992c.png)

**Comment by AkshGautam** [comment]
@therajanmaurya  I would like to take up this task

**Comment by therajanmaurya** [comment]
@AkshGautam Go ahead and send PR 👍

**Comment by AkshGautam** [comment]
PR #204 fixed it.Thanks
