### ISSUE TITLE
Disable Date of picker after current date in create customer

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/Fineract-CN-mobile#51]
**Summary:** 

Currently, the user can pick the upcoming date of birth of customer while creating a customer.
Date of birth can't be coming date. So disable the date picker after the coming dates.

**Steps to reproduce:** 

open client list and click on create customer fab button

**Expected behavior:** 

It should not show an option to pick date after present date.

**Observed behavior:** 

User can pick any date of birth including coming dates too.

**Comment by batbrain7** [comment]
@therajanmaurya I would like to fix this by adding a check on clicking the Ok button of the date picker,
which would check if the chosen date is ahead of the current date and show a prompt message and ask the user to chose the date again.

**Comment by therajanmaurya** [comment]
@batbrain7 This would not be a good solution, I prefer to disable the date section from the calendar after the current date.

**Comment by batbrain7** [comment]
@therajanmaurya thanks for the info, will submit a PR soon regarding this.

**Comment by therajanmaurya** [comment]
Fix in #201
