### ISSUE TITLE
Show Proper and user friendly text and image on failed to fetch anything

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/Fineract-CN-mobile#59]
**Summary:** 

Currently, the app is showing an image of and text that is not user-friendly to change text and image too with a good one.

**Comment by AkshGautam** [comment]
@therajanmaurya how should I reproduce the folllowing issue?

**Comment by batbrain7** [comment]
@therajanmaurya I would like to take up this issue, but could you please explain it a bit as there is very little information provided.

**Comment by therajanmaurya** [comment]
wait, My apologies, I think I solved it, yes I did Here we have Util class to handle every type of failure.

Closing the issue.
